### ISSUE TITLE
ebiten 1.10.0-alpha.4 seems to break ramen

### ISSUE THREAD

**Issue by csotherden** [BigJk/ramen#3] opened 2019-11-10 15:10 UTC
It seems that there was a change made to ebiten which dramatically breaks the functionality of ramen. I was able to trace through the release tags to find that the change seems to have been introduced in the 1.10.0-alpha.4 release tag but I haven't necessarily identified the specific commit within that release that broke things.

I'm using OS X 10.14.3 (18D109)

Here's a screenshot of ramen on 1.10.0-alpha.3 using the example from the readme:
<img width="556" alt="Screen Shot 2019-11-10 at 10 08 45 AM" src="https://user-images.githubusercontent.com/32003052/68546201-1e877300-03a2-11ea-9322-a92afdf3c929.png">

Here's a screenshot of ramen on 1.10.0-alpha.4 using the example from the readme:
<img width="558" alt="Screen Shot 2019-11-10 at 10 08 05 AM" src="https://user-images.githubusercontent.com/32003052/68546203-23e4bd80-03a2-11ea-9187-23913bcb306e.png">

All releases of ebiten post 1.10.0-alpha.3 seem to exhibit the behavior demonstrated above using the alpha.4 release.

**Comment by Urwumpe** [comment] 2019-11-12 14:00
I can confirm this, I see the same bug. Looks like op.SourceRect is depracted and no longer used, instead the ebiten.SubImage class is supposed to be used for the Drawing operations. I recommend fixing it in ToOptions by creating a SubImage object there first, before setting the other DrawingOptions. 

(I hope my comment is not too confusing, I still learn Go)

**Comment by BigJk** [comment] 2019-11-12 19:59
Thanks for the investigation. I will take a look at the problem as soon as I have time (probably in the coming days) 👍

**Comment by BigJk** [comment] 2019-11-12 20:55
e4b01feb350247ba52cf1a884b3d1e6d0c772513 I bumped the ebiten version to v1.10.0-alpha.4 and removed the use of the deprecated SourceRect option. It now extracts a SubImage like @Urwumpe said. Feel free to try out the latest commit and report back if it fixed the problems for you. The examples seem to work again on my side 😄

**Comment by csotherden** [comment] 2019-11-13 02:24
I just tested again with the latest commit and it seems to have resolved the issue.

**Comment by Urwumpe** [comment] 2019-11-13 08:48
I can also confirm that the bug is fixed and rendering works properly again. :)

**Comment by BigJk** [comment] 2019-11-13 09:34
Great. I will close the issue for now. If anything else arises feel free to re-open it or create a new issue 👍

**Closed as completed by BigJk** 2019-11-13 09:34 UTC
